### ISSUE TITLE
Should this plugin also replace "default" with the field name?

### ISSUE THREAD

**Issue by felipecrs** [krisztianb/typedoc-plugin-merge-modules#1]
First of all: your plugin saved my life. Thank you so much!

This started at https://github.com/TypeStrong/typedoc/issues/1521. So, now that all modules are merged, I think it does not make sense anymore to use "default" as the fieldname.

So, my point here is: should this plugin also replace "default" with the field name? I'm not asking to do, just discussing :).

![image](https://user-images.githubusercontent.com/29582865/110066731-e7846000-7d50-11eb-8b14-dffb24bcb854.png)

**Comment by felipecrs** [comment]
PS: this makes the API not browsable, as only one "default" link works.

**Comment by krisztianb** [comment]
Hi Felipe. I'm glad the plugin is useful for somebody.

If you look at the code you will see that the plugin does nothing fancy. It only moves all reflections from the modules into the project.

So the answer to your question is: No, it should not rename any exports at the moment. Naming collisions are not handled. I can have a look at that though.

What would be your expected output?

**Comment by felipecrs** [comment]
> No, it should not rename any exports at the moment. Naming collisions are not handled. 

I thought more about it, and I agree, you're right. Especially because users may want to do the "renaming" without using your plugin together, so it would be better to be a standalone plugin.

> What would be your expected output?

With TypeDoc 0.19 and `--mode files`, this is what I had: 

![image](https://user-images.githubusercontent.com/29582865/110120238-8c2b8f80-7d9b-11eb-92e9-dca02c096f6b.png)

Now, with TypeDoc 0.20 and your plugin:

![image](https://user-images.githubusercontent.com/29582865/110122097-f34a4380-7d9d-11eb-8c64-d40aecdf7a63.png)

Without your plugin:

![image](https://user-images.githubusercontent.com/29582865/110122322-3d332980-7d9e-11eb-9c3f-0477dfd4db98.png)

(despite the bad naming, they at least don't overlap)

PS: I'm using docusaurus, but I already tested and this behavior remains in vanilla TypeDoc html generator.

**Comment by krisztianb** [comment]
That would mean that moving the reflections to the project somehow destroys their "path". I'll take a look when I find the time. This should by fairly easy to reproduce with a simple example.

**Comment by felipecrs** [comment]
If you want, you can try with my repository:

https://github.com/felipecrs/megatar/tree/upgrade-typedoc/website
https://gitpod.io/#https://github.com/felipecrs/megatar/tree/upgrade-typedoc/website

**Comment by felipecrs** [comment]
@krisztianb fyi https://github.com/felipecrs/typedoc-plugin-rename-defaults

**Comment by krisztianb** [comment]
Interesting. Thanks for the heads up. I was thinking about adding an option (something like `renameDefaults: true|false`) to this plugin so that you don't need to create a separate one, since when merging modules this can be a common problem.

**Comment by felipecrs** [comment]
The main motivation for having a separate plugin is to be able to use it without your plugin.

**Comment by felipecrs** [comment]
I mean, for those who would still like to have their defaults renamed but they don't want to merge the modules. But the code itself is quite easy, as proposed by Gerrit0 at https://github.com/TypeStrong/typedoc/issues/1521#issuecomment-791971444.

**Comment by felipecrs** [comment]
I thought in these options:

- As you said, add the code and an option (and think about leaving the renameDefaults: true it by default, as it would cause the docs to overlap otherwise)
- Add typedoc-plugin-rename-defaults as dependency of yours, but I don't really know if that would work
- Simply document in the README, so who find this issue know what to do (install the typedoc-plugin-rename-defaults plugin)

**Comment by krisztianb** [comment]
I think `renameDefaults: true` makes a lot of sense. I don't think anybody wants to have something called `default` and moreover risk overwriting reflections when merging modules. I think I can add this option sometime next week.

**Comment by krisztianb** [comment]
New option `mergeModulesRenameDefaults` added in version 2.0.0. 🎉
