### ISSUE TITLE
Support for the Typedoc 0.26

### ISSUE THREAD

**Issue by Fancy2209** [krisztianb/typedoc-plugin-merge-modules#16]
I am using the Beta for the packageOptions property of tsconfig.json, but would prefer if the modules were all under the name of the Module like this plugin does, is there any way I could use it with 0.26.0-beta.2?

**Comment by krisztianb** [comment]
Did you run into any problems with the new TypeDoc version? I'm not planing to update the plugin until TypeDoc 0.26 is officially released.

**Comment by Fancy2209** [comment]
> Did you run into any problems with the new TypeDoc version? I'm not planing to update the plugin until TypeDoc 0.26 is officially released.

The peer depedencies don't have 0.26.x set so npm refuses to install it normally, and I fear i'll break something using legacy-peer-deps or force

**Comment by krisztianb** [comment]
Yeah, there is a reason I was defensive with defining the peer dependencies. Most major updates broke my plugins.

What do you think would break if you force the update?

Btw. you could change [this line](https://github.com/krisztianb/typedoc-plugin-merge-modules/blob/master/package.json#L30) in your `node_modules` folder to satisfy npm and see what happens.

**Comment by Fancy2209** [comment]
> Yeah, there is a reason I was defensive with defining the peer dependencies. Most major updates broke my plugins.
> 
> What do you think would break if you force the update?
> 
> Btw. you could change [this line](https://github.com/krisztianb/typedoc-plugin-merge-modules/blob/master/package.json#L30) in your `node_modules` folder to satisfy npm and see what happens.

I stopped beeing able to click classes and their icons dissapeared, it also didn't actually merge them
i guess I'll need to wait for 0.26 Stable, shame :/, it has 3 things I need (Proper Markdown in the On this page part of the sidebar, fix for using msys2 git instead (typedoc takes 2.5 hours making the docs if I don't use 0.26.0-beta.3!), packageOptions)

**Comment by ben-polinsky** [comment]
I was unable to get this plugin to work with the [packages entry point strategy](https://github.com/Gerrit0/typedoc-packages-example), FYI. I plan on getting a minimal reproduction up today. 

Edit: My bad, I see that was released in 0.25.12. I'll open a different issue if needed.

**Comment by krisztianb** [comment]
> I was unable to get this plugin to work with the [packages entry point strategy](https://github.com/Gerrit0/typedoc-packages-example), FYI. I plan on getting a minimal reproduction up today.
> 
> Edit: My bad, I see that was released in 0.25.12. I'll open a different issue if needed.

Hi Ben. You can find examples for monorepo setups (using the "packages" entry point strategy) in the test folder here on GitHub: https://github.com/krisztianb/typedoc-plugin-merge-modules/tree/master/test

Please take a look and compare your setup. If you still think that there is an issue with the plugin please open another issue. Thank you.

**Comment by ben-polinsky** [comment]
> Please take a look and compare your setup. If you still think that there is an issue with the plugin please open another issue. Thank you.

Appreciate it, will do.

**Comment by krisztianb** [comment]
TypeDoc 0.26 has been released and I can confirm that the plugin is no longer working correctly. Will have to debug the problem.

**Comment by krisztianb** [comment]
I published version **6.0.0** which should work with TypeDoc 0.26.x

Please try it and report back if you find any issues. Thank you.

**Comment by Fancy2209** [comment]
seems to work
