### ISSUE TITLE
Support for typedoc 0.27

### ISSUE THREAD

**Issue by bitboxer** [krisztianb/typedoc-plugin-merge-modules#22]
It would be nice if this plugin could be updated to 0.27. 

Thank you for your work on this.

**Comment by krisztianb** [comment]
Hi. A contributor already created a PR #21 for this. I hope I can get this done this weekend.

**Comment by krisztianb** [comment]
New version **6.1.0** released that supports TypeDoc 0.27.1 and above. (0.27.0 had a bug) 🎉
