### ISSUE TITLE
Difficulty using options

### ISSUE THREAD

**Issue by f-t-alves** [krisztianb/typedoc-plugin-merge-modules#8]
I have tried adding `"mergeModulesMergeMode": "module"` to my `typedoc.json` file, but now TypeDoc throws error `Error: Tried to set an option (mergeModulesMergeMode) that was not declared.`.

It does load `typedoc-plugin-merge-modules` right before throwing the error, so I believe I'm at fault for using the option the wrong way. How _should_ I use it, though?

**Comment by krisztianb** [comment]
That's strange. Which version of TypeDoc and typedoc-plugin-merge-modules are you using?

**Comment by f-t-alves** [comment]
TypeDoc: v0.22.6
typedoc-plugin-merge-modules: 3.0.2

**Comment by krisztianb** [comment]
Thanks. I'll try to reproduce the issue and will let you know what I found.

**Comment by krisztianb** [comment]
Unfortunately I can't reproduce your issue in my test project.

Do you have a public repository I could take a look at?

**Comment by f-t-alves** [comment]
Just to confirm, that is the correct usage, right? Unfortunately I can't share the repo as is, but I'll try to reproduce in an descaracterized project.

**Comment by f-t-alves** [comment]
Interesting, after a `yarn cache clean` and `yarn install`, it is now working as intended. Could've been some wonkiness during install yesterday. I will close the issue now.

Thank you for the time, sorry for the scare 😅
