### ISSUE TITLE
@packageDocumentation not behaving correctly

### ISSUE THREAD

**Issue by lageorgem** [krisztianb/typedoc-plugin-merge-modules#9]
Hello,

I was hoping I am able to specify a module-level documentation block by specifiying the @packageDocumentation annotation as per [these docs](https://typedoc.org/guides/doccomments/#files).
I am currently using your package as a replacement for [this obsolete package](https://github.com/christopherthielen/typedoc-plugin-external-module-name) which provided such a feature.
See [here](https://github.com/christopherthielen/typedoc-plugin-external-module-name#top-level-module-comments).

Would it be too much work to include this functionality?

**Comment by krisztianb** [comment]
Hi. What exactly is missing? Are you looking for the `@preferred` tag to be implemented or are `@packageDocumentation` tags ignored when merging the modules?

Could you post the version of TypeDoc and this plugin that you are using and also your TypeDoc config?

**Comment by lageorgem** [comment]
Hello. The following is my config, passed as arguments to the command:

```
typedoc --tsconfig ./tsconfig.json --mergeModulesMergeMode module --readme ./README.md --out docs/ src/
```

my versions:
```
"typedoc": "^0.21.9",
"typedoc-plugin-merge-modules": "^3.0.2",
```

I think I am looking for both. Currently I have a doc comment that looks like this

```
/ *
 * Comment content
 * @packageDocumentation
 * @module Transformation
 * @preferred
 */
```

This comment does not appear on the index for the Transformation module. In fact, it does not appear anywhere.
I was hoping to be able to add a documentation page for the home page of a module in order to explain how it works properly.

**Comment by krisztianb** [comment]
I'm not familiar with these module comments but I will take a look and report back to you.

PS: You need to start the comment with `/**` right?

**Comment by krisztianb** [comment]
I released 3.1.0 which adds the functionality you are looking for. Instead of `@preferred` you need to use `@mergeTarget`. You only need to use this new tag if more than one of the modules that are merged have a comment.

Please see if it works as expected and report back so we can close this issue. Thanks.

**Comment by lageorgem** [comment]
It works wonderful. Thank you very much for the incredibly quick response and fix.

**Comment by krisztianb** [comment]
Glad to hear. Please report back if you find any issues.
